default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
development:
  <<: *default
  database: bookstore2_development

# test:
#   <<: *default
#   database: bookstore2_test

# production:
#   <<: *default
#   database: bookstore2_production
#   username: bookstore2
#   password: <%= ENV['BOOKSTORE2_DATABASE_PASSWORD'] %>
