default: &default
  adapter: postgresql
  encoding: unicode
  # collation: utf8mb4_unicode_ci
  host: <%= ENV['DB_HOST'] %>
  username: khanh
  password: password
  # password: 1510
development:
  <<: *default
  database: bookstore2_development

test:
  <<: *default
  database: bookstore2_test

# production:
#   <<: *default
#   database: bookstore2_production
#   username: bookstore2
#   password: <%= ENV['BOOKSTORE2_DATABASE_PASSWORD'] %>
