# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql2
        ports:
          - "8080:8080"
        env:
          MYSQL_DATABASE: bookstore2_test
          MYSQL_USER: root
          MYSQL_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "mysql2://root:password@localhost:5432/bookstore2_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.161.0
        with:
            bundler-cache: true
        # Add or replace dependency steps here
      # - name: Install Ruby and gems
      #   uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rails spec

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
  #       with:
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
